spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graph
    username: root
    password: Edu19-94

  graphql:
    graphiql:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    sql: debug
    web: debug


